### ISSUE TITLE
Error running Console project

### ISSUE THREAD

**Issue by jlribas** [jatinrdave/SQLEFTableNotification#1]
Hello,

I'm trying to run the console project without any modification.

It throws this exception at line 17 of Program.cs:
```
System.ArgumentException
  HResult=0x80070057
  Message=Arity of open generic service type 'SQLEFTableNotification.Interfaces.IChangeTableService`1[T]' does not equal arity of open generic implementation type 'SQLEFTableNotification.Console.Services.ChangeTableService`2[T,TView]'. Arg_ParamName_Name
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at MainProgram.Main() in C:\Users\jlribas\Source\Repos\SQLEFTableNotification_ORIGINAL\SQLEFTableNotification.Console\Program.cs:line 17
```

I've tried to instantiate a new SQLTableMonitorManager creating some objects without serviceProvider, but the compiler complains with another error that I don't know how to solve: 
```
 public static void Main()
    {
        var serviceProvider = new ServiceCollection()
                 .AddScoped(typeof(IChangeTableService<>), typeof(ChangeTableService<,>))
                 .AddScoped<ISQLTableMonitorManager, SQLTableMonitorManager>()
        .BuildServiceProvider();

        IUnitOfWork unitOfWork = serviceProvider.GetService<IUnitOfWork>();
        IMapper mapper = serviceProvider.GetService<Mapper>();

        ChangeTableService<User, UserViewModel> changeTableService = new ChangeTableService<User, UserViewModel>(unitOfWork, mapper);
        UserServiceAsync<UserViewModel, User> userService = new UserServiceAsync<UserViewModel, User>(unitOfWork, mapper);

        ISQLTableMonitorManager tableMonitorManager = new SQLTableMonitorManager(changeTableService, userService);      
        Task.Run( async()=> await tableMonitorManager.Invoke()).Wait();
    }

Error	CS1503	Argument 1: cannot convert from 'SQLEFTableNotification.Console.Services.ChangeTableService<SQLEFTableNotification.Entity.User, SQLEFTableNotification.Domain.UserViewModel>' to 'SQLEFTableNotification.Interfaces.IChangeTableService<SQLEFTableNotification.Entity.Entity.UserChangeTable>'	SQLEFTableNotification.Console	C:\Users\jlribas\Source\Repos\SQLEFTableNotification_ORIGINAL\SQLEFTableNotification.Console\Program.cs	33

```

Any suggestions?

**Comment by Mephisztoe** [comment]
I can copy that.

This is due to the fact that from net6 on, registering services won't work this way anymore. Funny enough: It didn't work with net5 either. It's just that the runtime didn't throw an error as long as you didn't try to request such an instance.

However, even you manage to unwrap this registration there are still some missing pieces I don't understand:
Going down the rabbit hole of injected dependencies you will notice that the app also needs to know where to get an instance of IUnitOfWork as well as a profile for the AutoMapper. Also there needs to be some DbContext around and even then, it won't work.

I was also wondering about the easy integration of SQLEFTableNotification into own projects, since this implementation is tightly coupled to so many interfaces and classes that belong to this very demo project that it's a really pain in the bottom pulling everything apart for simple use in actual own projects (that even don't rely on Entity Framework).

However... This project is awesome nonetheless! Its code is high sophisticated and able to achieve something, Microsoft didn't provide a solution for (yet).

I believe, somebody should strip off every external dependency and put everything nicely into a nuget package to reference and simply use...

**Comment by Mephisztoe** [comment]
I need to add some thoughts on my last post. The demo repository does indeed contain the classes necessary to integrate this solution into own projects. I was just overwhelmed by all the projects and patterns used. :)

You basically only have to implement the IChangeTableService Interface and stuff it with whatever you need to access your Database and execute queries and then create an instance of SqlDBNotificationService.

There's some utility classes you'd need like ChangeTables or VersionCount Tables and such and then you can decide whether to put some of the entity classes like ChangeTable into your own project or reference the Entity project of this repo and also get all that nice Unit of Work pattern stuff. :)

**Comment by jatinrdave** [comment]
https://medium.com/@techbrainhub/announcing-sqldbentitynotifier-effortless-real-time-sql-server-change-tracking-for-net-404a4e027eeb
